import gradio as gr
from chain_logic import query_database  # Import the main logic

# Create Gradio interface
with gr.Blocks(title="NLP to SQL Query Interface", theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        # 🗄️ Natural Language to SQL Query Interface
        
        Ask questions about the Walmart sales data in plain English, and get:
        - The actual SQL query that was executed
        - The database results
        - A natural language explanation of the results
        
        ### Example Questions:
        - "What is the total revenue for each branch?"
        - "Which product line has the highest average rating?"
        - "Show me the top 5 cities by total sales"
        - "Compare revenue between male and female customers"
        """
    )
    
    with gr.Row():
        with gr.Column():
            question_input = gr.Textbox(
                label="Your Question",
                placeholder="e.g., What are the top 3 product lines by revenue?",
                lines=3
            )
            submit_btn = gr.Button("🔍 Execute Query", variant="primary", size="lg")
            
            gr.Markdown("### Quick Examples:")
            example_questions = [
                "Find the total revenue generated by each branch",
                "What are the top 3 product lines with the highest average rating?",
                "Which payment method generates the highest average gross income?",
                "Show me monthly sales trends",
                "Compare average spending between Member and Normal customers"
            ]
            
            for eq in example_questions:
                gr.Button(eq, size="sm").click(
                    fn=lambda x=eq: x,
                    outputs=question_input
                )
    
    with gr.Row():
        with gr.Column():
            gr.Markdown("### 📝 Generated SQL Query")
            sql_output = gr.Code(label="SQL Query", language="sql", lines=8)
    
    with gr.Row():
        with gr.Column():
            gr.Markdown("### 📊 Database Results")
            result_output = gr.Dataframe(label="Query Results", wrap=True)
    
    with gr.Row():
        with gr.Column():
            gr.Markdown("### 💡 Natural Language Explanation")
            explanation_output = gr.Textbox(
                label="Explanation",
                lines=6,
                show_copy_button=True
            )
    
    # Connect the button to the function
    submit_btn.click(
        fn=query_database,
        inputs=[question_input],
        outputs=[sql_output, result_output, explanation_output]
    )
    
    gr.Markdown(
        """
        ---
        **Note:** This interface connects to your Walmart sales database and uses Google's Gemini AI 
        to translate natural language questions into SQL queries.
        """
    )

# Launch the interface
if __name__ == "__main__":
    print("Launching Gradio Interface...")
    demo.launch(share=True, debug=True)